//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentMe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentMe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to add items to your cart first!.
        /// </summary>
        internal static string addItemsToCart {
            get {
                return ResourceManager.GetString("addItemsToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check input boxes for errors.
        /// </summary>
        internal static string CheckInputBoxesForErrors {
            get {
                return ResourceManager.GetString("CheckInputBoxesForErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer selected: .
        /// </summary>
        internal static string customerSelected {
            get {
                return ResourceManager.GetString("customerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items are selected. To delete: select items first, then press delete..
        /// </summary>
        internal static string deleteErrorMessage {
            get {
                return ResourceManager.GetString("deleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        ///.
        /// </summary>
        internal static string deleteFailed {
            get {
                return ResourceManager.GetString("deleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string dollarSign {
            get {
                return ResourceManager.GetString("dollarSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query cannot be empty..
        /// </summary>
        internal static string emptyQueryMessage {
            get {
                return ResourceManager.GetString("emptyQueryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one rental to return.
        /// </summary>
        internal static string emptyRentals {
            get {
                return ResourceManager.GetString("emptyRentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and Last name must be filled in order to perform search.
        /// </summary>
        internal static string FirstAndLastNameMustBeFilled {
            get {
                return ResourceManager.GetString("FirstAndLastNameMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***-**-.
        /// </summary>
        internal static string hiddenSSN {
            get {
                return ResourceManager.GetString("hiddenSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information has been updated.
        /// </summary>
        internal static string informationHasBeenUpdated {
            get {
                return ResourceManager.GetString("informationHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert failed.
        ///.
        /// </summary>
        internal static string insertFailed {
            get {
                return ResourceManager.GetString("insertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per day.
        /// </summary>
        internal static string perDay {
            get {
                return ResourceManager.GetString("perDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query failed: 
        ///.
        /// </summary>
        internal static string queryFailed {
            get {
                return ResourceManager.GetString("queryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental order placed successfully. We will send you reminder emails when each of your rentals is due. Have a great day!.
        /// </summary>
        internal static string rentalSuccessful {
            get {
                return ResourceManager.GetString("rentalSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generation Failed..
        /// </summary>
        internal static string reportGenerationFailed {
            get {
                return ResourceManager.GetString("reportGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return processed, please settle any penalties you may owe. (Note: any items that have already been returned were excluded from this transaction).
        /// </summary>
        internal static string returnSuccessful {
            get {
                return ResourceManager.GetString("returnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a customer before a cart can be created.
        /// </summary>
        internal static string selectACustomerBeforeCartCreation {
            get {
                return ResourceManager.GetString("selectACustomerBeforeCartCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a customer before you can view transactions.
        /// </summary>
        internal static string selectACustomerBeforeTransactionViewing {
            get {
                return ResourceManager.GetString("selectACustomerBeforeTransactionViewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string space {
            get {
                return ResourceManager.GetString("space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Query failed..
        /// </summary>
        internal static string sqlQueryFailed {
            get {
                return ResourceManager.GetString("sqlQueryFailed", resourceCulture);
            }
        }
    }
}
